### ISSUE TITLE
Verify Sketch

### ISSUE THREAD

**Issue by triptaker27** [AM-STUDIO/E36_CLUSTER_SIMHUB#1]
Hello,
I have selected the correct Arduino board and the correct port. As I click on the check mark "Verify", I receive an error message. 

Arduino: 1.8.7 (Windows 10), Board: "Arduino/Genuino Uno"

DisplayClientV2:81:1: error: 'include' does not name a type

 include "TM1637.h"

 ^

DisplayClientV2:382:1: error: 'Tone' does not name a type

 Tone rpmTone;

 ^

C:\Users\STORMY\Desktop\E36_CLUSTER_SIMHUB-master\DisplayClientV2\DisplayClientV2.ino: In function 'void setup()':

DisplayClientV2:755:23: error: 'FlowSerialBegin' was not declared in this scope

  FlowSerialBegin(19200);

                       ^

DisplayClientV2:857:3: error: 'rpmTone' was not declared in this scope

   rpmTone.begin(pinTacho);

   ^

C:\Users\STORMY\Desktop\E36_CLUSTER_SIMHUB-master\DisplayClientV2\DisplayClientV2.ino: In function 'void sendButtonState()':

DisplayClientV2:1066:62: error: 'FlowSerialWrite' was not declared in this scope

   FlowSerialWrite(digitalRead(BUTTON_PINS[i]) == HIGH ? 0 : 1);

                                                              ^

DisplayClientV2:1069:18: error: 'FlowSerialFlush' was not declared in this scope

  FlowSerialFlush();

                  ^

C:\Users\STORMY\Desktop\E36_CLUSTER_SIMHUB-master\DisplayClientV2\DisplayClientV2.ino: In function 'void SetBaudrate()':

DisplayClientV2:1138:31: error: 'FlowSerialTimedRead' was not declared in this scope

  int br = FlowSerialTimedRead();

                               ^

DisplayClientV2:1142:34: error: 'FlowSerialBegin' was not declared in this scope

  if (br == 1) FlowSerialBegin(300);

                                  ^

DisplayClientV2:1143:35: error: 'FlowSerialBegin' was not declared in this scope

  if (br == 2) FlowSerialBegin(1200);

                                   ^

DisplayClientV2:1144:35: error: 'FlowSerialBegin' was not declared in this scope

  if (br == 3) FlowSerialBegin(2400);

                                   ^

DisplayClientV2:1145:35: error: 'FlowSerialBegin' was not declared in this scope

  if (br == 4) FlowSerialBegin(4800);

                                   ^

DisplayClientV2:1146:35: error: 'FlowSerialBegin' was not declared in this scope

  if (br == 5) FlowSerialBegin(9600);

                                   ^

DisplayClientV2:1147:36: error: 'FlowSerialBegin' was not declared in this scope

  if (br == 6) FlowSerialBegin(14400);

                                    ^

DisplayClientV2:1148:36: error: 'FlowSerialBegin' was not declared in this scope

  if (br == 7) FlowSerialBegin(19200);

                                    ^

DisplayClientV2:1149:36: error: 'FlowSerialBegin' was not declared in this scope

  if (br == 8) FlowSerialBegin(28800);

                                    ^

DisplayClientV2:1150:36: error: 'FlowSerialBegin' was not declared in this scope

  if (br == 9) FlowSerialBegin(38400);

                                    ^

DisplayClientV2:1151:37: error: 'FlowSerialBegin' was not declared in this scope

  if (br == 10) FlowSerialBegin(57600);

                                     ^

DisplayClientV2:1152:38: error: 'FlowSerialBegin' was not declared in this scope

  if (br == 11) FlowSerialBegin(115200);

                                      ^

DisplayClientV2:1153:38: error: 'FlowSerialBegin' was not declared in this scope

  if (br == 12) FlowSerialBegin(230400);

                                      ^

DisplayClientV2:1154:38: error: 'FlowSerialBegin' was not declared in this scope

  if (br == 13) FlowSerialBegin(250000);

                                      ^

DisplayClientV2:1155:39: error: 'FlowSerialBegin' was not declared in this scope

  if (br == 14) FlowSerialBegin(1000000);

                                       ^

DisplayClientV2:1156:39: error: 'FlowSerialBegin' was not declared in this scope

  if (br == 15) FlowSerialBegin(2000000);

                                       ^

DisplayClientV2:1157:38: error: 'FlowSerialBegin' was not declared in this scope

  if (br == 16) FlowSerialBegin(200000);

                                      ^

C:\Users\STORMY\Desktop\E36_CLUSTER_SIMHUB-master\DisplayClientV2\DisplayClientV2.ino: In function 'void loop()':

DisplayClientV2:1211:26: error: 'FlowSerialAvailable' was not declared in this scope

  if (FlowSerialAvailable() > 0) {

                          ^

DisplayClientV2:1213:27: error: 'FlowSerialRead' was not declared in this scope

   header = FlowSerialRead();

                           ^

DisplayClientV2:1218:30: error: 'FlowSerialTimedRead' was not declared in this scope

    opt = FlowSerialTimedRead();

                              ^

DisplayClientV2:1222:5: error: 'FlowSerialTrigger' was not declared in this scope

     FlowSerialTrigger = FlowSerialTimedRead();

     ^

DisplayClientV2:1224:24: error: 'FlowSerialPrint' was not declared in this scope

     FlowSerialPrint('h');

                        ^

DisplayClientV2:1225:21: error: 'FlowSerialFlush' was not declared in this scope

     FlowSerialFlush();

                     ^

DisplayClientV2:1235:50: error: 'FlowSerialWrite' was not declared in this scope

     FlowSerialWrite((byte)(ENABLED_BUTTONS_COUNT));

                                                  ^

DisplayClientV2:1236:21: error: 'FlowSerialFlush' was not declared in this scope

     FlowSerialFlush();

                     ^

DisplayClientV2:1241:50: error: 'FlowSerialWrite' was not declared in this scope

     FlowSerialWrite((byte)(TM1638_ENABLEDMODULES));

                                                  ^

DisplayClientV2:1242:21: error: 'FlowSerialFlush' was not declared in this scope

     FlowSerialFlush();

                     ^

DisplayClientV2:1247:106: error: 'FlowSerialWrite' was not declared in this scope

     FlowSerialWrite((byte)(MAX7221_ENABLEDMODULES + TM1637_ENABLEDMODULES + ENABLE_ADA_HT16K33_7SEGMENTS));

                                                                                                          ^

DisplayClientV2:1248:21: error: 'FlowSerialFlush' was not declared in this scope

     FlowSerialFlush();

                     ^

DisplayClientV2:1253:25: error: 'FlowSerialWrite' was not declared in this scope

     FlowSerialWrite(0x03);

                         ^

DisplayClientV2:1254:21: error: 'FlowSerialFlush' was not declared in this scope

     FlowSerialFlush();

                     ^

DisplayClientV2:1260:21: error: 'FlowSerialFlush' was not declared in this scope

     FlowSerialFlush();

                     ^

DisplayClientV2:1265:21: error: 'DEVICE_NAME' was not declared in this scope

     FlowSerialPrint(DEVICE_NAME);

                     ^

DisplayClientV2:1265:32: error: 'FlowSerialPrint' was not declared in this scope

     FlowSerialPrint(DEVICE_NAME);

                                ^

DisplayClientV2:1267:21: error: 'FlowSerialFlush' was not declared in this scope

     FlowSerialFlush();

                     ^

DisplayClientV2:1273:46: error: 'FlowSerialReadStringUntil' was not declared in this scope

     int freq = FlowSerialReadStringUntil('\n').toInt();

                                              ^

DisplayClientV2:1275:6: error: 'rpmTone' was not declared in this scope

      rpmTone.play(freq);

      ^

DisplayClientV2:1279:6: error: 'rpmTone' was not declared in this scope

      rpmTone.stop();

      ^

DisplayClientV2:1299:25: error: 'FlowSerialPrint' was not declared in this scope

      FlowSerialPrint("M");

                         ^

DisplayClientV2:1310:25: error: 'FlowSerialPrint' was not declared in this scope

      FlowSerialPrint("K");

                         ^

DisplayClientV2:1314:24: error: 'FlowSerialPrint' was not declared in this scope

     FlowSerialPrint("G");

                        ^

DisplayClientV2:1348:21: error: 'FlowSerialFlush' was not declared in this scope

     FlowSerialFlush();

                     ^

DisplayClientV2:1430:69: error: 'FlowSerialWrite' was not declared in this scope

     FlowSerialWrite((byte)(WS2812B_RGBLEDCOUNT + WS2801_RGBLEDCOUNT));

                                                                     ^

DisplayClientV2:1431:21: error: 'FlowSerialFlush' was not declared in this scope

     FlowSerialFlush();

                     ^

DisplayClientV2:1472:25: error: 'FlowSerialWrite' was not declared in this scope

     FlowSerialWrite(0x15);

                         ^

DisplayClientV2:1488:25: error: 'FlowSerialWrite' was not declared in this scope

     FlowSerialWrite(0x15);

                         ^

C:\Users\STORMY\Desktop\E36_CLUSTER_SIMHUB-master\DisplayClientV2\DisplayClientV2.ino: At global scope:

DisplayClientV2:1709:1: error: 'Tone' does not name a type

 Tone e36SppedTone;

 ^

C:\Users\STORMY\Desktop\E36_CLUSTER_SIMHUB-master\DisplayClientV2\DisplayClientV2.ino: In function 'void CustomProtocolExample3_E36Speedo()':

DisplayClientV2:1717:3: error: 'e36SppedTone' was not declared in this scope

   e36SppedTone.begin(speedPin);

   ^

DisplayClientV2:1721:43: error: 'FlowSerialReadStringUntil' was not declared in this scope

  int speed = FlowSerialReadStringUntil(';').toInt();

                                           ^

C:\Users\STORMY\Desktop\E36_CLUSTER_SIMHUB-master\DisplayClientV2\DisplayClientV2.ino:1729:34: warning: expression list treated as compound expression in functional cast [-fpermissive]

 int speedcorrect = int(speed, HEX);

                                  ^

DisplayClientV2:1731:3: error: 'e36SppedTone' was not declared in this scope

   e36SppedTone.stop();

   ^

DisplayClientV2:1734:3: error: 'e36SppedTone' was not declared in this scope

   e36SppedTone.play(speedoutput);

   ^

exit status 1
'include' does not name a type

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by ThatRedTruck** [comment]
Did you eventually solve this? cause I'm getting errors while verifying as well

**Comment by jimmycaille** [comment]
Hi, I just received this notification because I watch the project since a couple of month after seeing the youtube video. A while back, I tested the sketch and I think I also had problems...

- The first error is related to the TM1637 library that you need to import (search on google the procedure if you are new with the Arduino IDE).
- For the FlowSerialRead, the FlowSerialRead.h file has to be in the same folder as the DisplayClientV2.ino file.

Then everything seems to be related...
Try that and tell me if it solves your problem

**Comment by triptaker27** [comment]
> Did you eventually solve this? cause I'm getting errors while verifying as well

**Comment by Danigy6196** [comment]
hello, I also have these errors, if someone can help I will be very grateful

![image](https://user-images.githubusercontent.com/81564552/198556091-885538e6-7ef4-42a5-933c-d36cc161b87c.png)

**Comment by jimmycaille** [comment]
Check my previous comment, you have to install the Adafruit I2C library in the Arduino IDE.
There are plenty of how-tos online about that
